//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.TelhaNorteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", ConfigurationName="TelhaNorteService.Services_PortType")]
    public interface Services_PortType {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (activateOffer_Request) da mensagem activateOfferRequest não corresponde ao valor padrão (activateOffer)
        [System.ServiceModel.OperationContractAttribute(Action="SGDBServicesAPI_API_SOAP_Services_Binder_activateOffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Infrastructure.TelhaNorteService.activateOfferResponse activateOffer(Infrastructure.TelhaNorteService.activateOfferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SGDBServicesAPI_API_SOAP_Services_Binder_activateOffer", ReplyAction="*")]
        System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.activateOfferResponse> activateOfferAsync(Infrastructure.TelhaNorteService.activateOfferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SGDBServicesAPI_API_SOAP_Services_Binder_getOrdersByDocumentID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Infrastructure.TelhaNorteService.getOrdersByDocumentIDResponse getOrdersByDocumentID(Infrastructure.TelhaNorteService.getOrdersByDocumentIDRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="SGDBServicesAPI_API_SOAP_Services_Binder_getOrdersByDocumentID", ReplyAction="*")]
        System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.getOrdersByDocumentIDResponse> getOrdersByDocumentIDAsync(Infrastructure.TelhaNorteService.getOrdersByDocumentIDRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (createUpdateCustomer_Request) da mensagem createUpdateCustomerRequest não corresponde ao valor padrão (createUpdateCustomer)
        [System.ServiceModel.OperationContractAttribute(Action="SGDBServicesAPI_API_SOAP_Services_Binder_createUpdateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Infrastructure.TelhaNorteService.createUpdateCustomerResponse createUpdateCustomer(Infrastructure.TelhaNorteService.createUpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SGDBServicesAPI_API_SOAP_Services_Binder_createUpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.createUpdateCustomerResponse> createUpdateCustomerAsync(Infrastructure.TelhaNorteService.createUpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SGDBServicesAPI_API_SOAP_Services_Binder_getCustomerByDocumentID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Infrastructure.TelhaNorteService.getCustomerByDocumentIDResponse getCustomerByDocumentID(Infrastructure.TelhaNorteService.getCustomerByDocumentIDRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="SGDBServicesAPI_API_SOAP_Services_Binder_getCustomerByDocumentID", ReplyAction="*")]
        System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.getCustomerByDocumentIDResponse> getCustomerByDocumentIDAsync(Infrastructure.TelhaNorteService.getCustomerByDocumentIDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30:5555/SGDBServicesAPI/")]
    public partial class headerDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appKeyField;
        
        private System.Nullable<System.DateTime> dateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", IsNullable=true, Order=0)]
        public string AppKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("AppKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("dateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zipCodeField;
        
        private string nameField;
        
        private System.Nullable<int> numberField;
        
        private string complementField;
        
        private string neighborhoodField;
        
        private string cityField;
        
        private System.Nullable<state> stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string complement {
            get {
                return this.complementField;
            }
            set {
                this.complementField = value;
                this.RaisePropertyChanged("complement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string neighborhood {
            get {
                return this.neighborhoodField;
            }
            set {
                this.neighborhoodField = value;
                this.RaisePropertyChanged("neighborhood");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<state> state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public enum state {
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AP,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        DF,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        GO,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PI,
        
        /// <remarks/>
        RJ,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RR,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        TO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentIDField;
        
        private string nameField;
        
        private System.Nullable<gender> genderField;
        
        private System.Nullable<System.DateTime> dateOfBirthField;
        
        private string rgField;
        
        private System.Nullable<placeOfBirth> placeOfBirthField;
        
        private string nationalityField;
        
        private string homePhoneField;
        
        private string mobilePhoneField;
        
        private System.Nullable<bool> smsOptinField;
        
        private System.Nullable<int> professionalActivityField;
        
        private bool professionalActivityFieldSpecified;
        
        private string emailField;
        
        private Address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string documentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
                this.RaisePropertyChanged("documentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<gender> gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("dateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
                this.RaisePropertyChanged("rg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<placeOfBirth> placeOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                this.placeOfBirthField = value;
                this.RaisePropertyChanged("placeOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string homePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("homePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string mobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("mobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<bool> smsOptin {
            get {
                return this.smsOptinField;
            }
            set {
                this.smsOptinField = value;
                this.RaisePropertyChanged("smsOptin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<int> professionalActivity {
            get {
                return this.professionalActivityField;
            }
            set {
                this.professionalActivityField = value;
                this.RaisePropertyChanged("professionalActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool professionalActivitySpecified {
            get {
                return this.professionalActivityFieldSpecified;
            }
            set {
                this.professionalActivityFieldSpecified = value;
                this.RaisePropertyChanged("professionalActivitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public enum gender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public enum placeOfBirth {
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AP,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        DF,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        GO,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PI,
        
        /// <remarks/>
        RJ,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RR,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        TO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class customerDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Customer customerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class Paging : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> totalField;
        
        private System.Nullable<int> currentPageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class Items : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> skuIDField;
        
        private string productNameField;
        
        private string categoryLevel1Field;
        
        private string categoryLevel2Field;
        
        private string categoryLevel3Field;
        
        private string categoryLevel4Field;
        
        private string categoryLevel5Field;
        
        private string categoryLevel6Field;
        
        private System.Nullable<int> eANField;
        
        private string manufacturingLotField;
        
        private System.Nullable<decimal> quantityField;
        
        private System.Nullable<decimal> priceField;
        
        private System.Nullable<decimal> discountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> skuID {
            get {
                return this.skuIDField;
            }
            set {
                this.skuIDField = value;
                this.RaisePropertyChanged("skuID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string categoryLevel1 {
            get {
                return this.categoryLevel1Field;
            }
            set {
                this.categoryLevel1Field = value;
                this.RaisePropertyChanged("categoryLevel1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string categoryLevel2 {
            get {
                return this.categoryLevel2Field;
            }
            set {
                this.categoryLevel2Field = value;
                this.RaisePropertyChanged("categoryLevel2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string categoryLevel3 {
            get {
                return this.categoryLevel3Field;
            }
            set {
                this.categoryLevel3Field = value;
                this.RaisePropertyChanged("categoryLevel3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string categoryLevel4 {
            get {
                return this.categoryLevel4Field;
            }
            set {
                this.categoryLevel4Field = value;
                this.RaisePropertyChanged("categoryLevel4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string categoryLevel5 {
            get {
                return this.categoryLevel5Field;
            }
            set {
                this.categoryLevel5Field = value;
                this.RaisePropertyChanged("categoryLevel5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string categoryLevel6 {
            get {
                return this.categoryLevel6Field;
            }
            set {
                this.categoryLevel6Field = value;
                this.RaisePropertyChanged("categoryLevel6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> EAN {
            get {
                return this.eANField;
            }
            set {
                this.eANField = value;
                this.RaisePropertyChanged("EAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string manufacturingLot {
            get {
                return this.manufacturingLotField;
            }
            set {
                this.manufacturingLotField = value;
                this.RaisePropertyChanged("manufacturingLot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<decimal> quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<decimal> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public System.Nullable<decimal> discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
                this.RaisePropertyChanged("discount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class Orders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> numDocumentField;
        
        private System.Nullable<int> idCompanyField;
        
        private string companyNameField;
        
        private string shippingTypeField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private System.Nullable<decimal> totalOrderField;
        
        private string statusField;
        
        private Items[] listOfItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> numDocument {
            get {
                return this.numDocumentField;
            }
            set {
                this.numDocumentField = value;
                this.RaisePropertyChanged("numDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> idCompany {
            get {
                return this.idCompanyField;
            }
            set {
                this.idCompanyField = value;
                this.RaisePropertyChanged("idCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("companyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string shippingType {
            get {
                return this.shippingTypeField;
            }
            set {
                this.shippingTypeField = value;
                this.RaisePropertyChanged("shippingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<decimal> totalOrder {
            get {
                return this.totalOrderField;
            }
            set {
                this.totalOrderField = value;
                this.RaisePropertyChanged("totalOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Items[] ListOfItems {
            get {
                return this.listOfItemsField;
            }
            set {
                this.listOfItemsField = value;
                this.RaisePropertyChanged("ListOfItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class ordersDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Orders[] listOfOrdersField;
        
        private Paging pagingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Orders[] ListOfOrders {
            get {
                return this.listOfOrdersField;
            }
            set {
                this.listOfOrdersField = value;
                this.RaisePropertyChanged("ListOfOrders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Paging Paging {
            get {
                return this.pagingField;
            }
            set {
                this.pagingField = value;
                this.RaisePropertyChanged("Paging");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class returnDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<status> statusField;
        
        private System.Nullable<decimal> idControlField;
        
        private bool idControlFieldSpecified;
        
        private string processMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<status> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<decimal> idControl {
            get {
                return this.idControlField;
            }
            set {
                this.idControlField = value;
                this.RaisePropertyChanged("idControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idControlSpecified {
            get {
                return this.idControlFieldSpecified;
            }
            set {
                this.idControlFieldSpecified = value;
                this.RaisePropertyChanged("idControlSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string processMessage {
            get {
                return this.processMessageField;
            }
            set {
                this.processMessageField = value;
                this.RaisePropertyChanged("processMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public enum status {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class Offer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentIDField;
        
        private string idGroupOfferField;
        
        private System.Nullable<int> skuIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string documentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
                this.RaisePropertyChanged("documentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string idGroupOffer {
            get {
                return this.idGroupOfferField;
            }
            set {
                this.idGroupOfferField = value;
                this.RaisePropertyChanged("idGroupOffer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> skuID {
            get {
                return this.skuIDField;
            }
            set {
                this.skuIDField = value;
                this.RaisePropertyChanged("skuID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services")]
    public partial class offerDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Offer offerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Offer Offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
                this.RaisePropertyChanged("Offer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateOffer_Request", WrapperNamespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", IsWrapped=true)]
    public partial class activateOfferRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://10.199.68.30:5555/SGDBServicesAPI/")]
        public Infrastructure.TelhaNorteService.headerDTO auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Infrastructure.TelhaNorteService.offerDTO OfferDTO;
        
        public activateOfferRequest() {
        }
        
        public activateOfferRequest(Infrastructure.TelhaNorteService.headerDTO auth, Infrastructure.TelhaNorteService.offerDTO OfferDTO) {
            this.auth = auth;
            this.OfferDTO = OfferDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateOffer_Response", WrapperNamespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", IsWrapped=true)]
    public partial class activateOfferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Infrastructure.TelhaNorteService.returnDTO ReturnDTO;
        
        public activateOfferResponse() {
        }
        
        public activateOfferResponse(Infrastructure.TelhaNorteService.returnDTO ReturnDTO) {
            this.ReturnDTO = ReturnDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrdersByDocumentID_Request", WrapperNamespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", IsWrapped=true)]
    public partial class getOrdersByDocumentIDRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://10.199.68.30:5555/SGDBServicesAPI/")]
        public Infrastructure.TelhaNorteService.headerDTO auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string documentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> referenceDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> pageNumber;
        
        public getOrdersByDocumentIDRequest() {
        }
        
        public getOrdersByDocumentIDRequest(Infrastructure.TelhaNorteService.headerDTO auth, string documentID, System.Nullable<System.DateTime> referenceDateTime, System.Nullable<int> pageNumber) {
            this.auth = auth;
            this.documentID = documentID;
            this.referenceDateTime = referenceDateTime;
            this.pageNumber = pageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrdersByDocumentID_Response", WrapperNamespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", IsWrapped=true)]
    public partial class getOrdersByDocumentIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Infrastructure.TelhaNorteService.ordersDTO OrdersDTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Infrastructure.TelhaNorteService.returnDTO ReturnDTO;
        
        public getOrdersByDocumentIDResponse() {
        }
        
        public getOrdersByDocumentIDResponse(Infrastructure.TelhaNorteService.ordersDTO OrdersDTO, Infrastructure.TelhaNorteService.returnDTO ReturnDTO) {
            this.OrdersDTO = OrdersDTO;
            this.ReturnDTO = ReturnDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUpdateCustomer_Request", WrapperNamespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", IsWrapped=true)]
    public partial class createUpdateCustomerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://10.199.68.30:5555/SGDBServicesAPI/")]
        public Infrastructure.TelhaNorteService.headerDTO auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Infrastructure.TelhaNorteService.customerDTO CustomerDTO;
        
        public createUpdateCustomerRequest() {
        }
        
        public createUpdateCustomerRequest(Infrastructure.TelhaNorteService.headerDTO auth, Infrastructure.TelhaNorteService.customerDTO CustomerDTO) {
            this.auth = auth;
            this.CustomerDTO = CustomerDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUpdateCustomer_Response", WrapperNamespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", IsWrapped=true)]
    public partial class createUpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Infrastructure.TelhaNorteService.returnDTO ReturnDTO;
        
        public createUpdateCustomerResponse() {
        }
        
        public createUpdateCustomerResponse(Infrastructure.TelhaNorteService.returnDTO ReturnDTO) {
            this.ReturnDTO = ReturnDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerByDocumentID_Request", WrapperNamespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", IsWrapped=true)]
    public partial class getCustomerByDocumentIDRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://10.199.68.30:5555/SGDBServicesAPI/")]
        public Infrastructure.TelhaNorteService.headerDTO auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string documentID;
        
        public getCustomerByDocumentIDRequest() {
        }
        
        public getCustomerByDocumentIDRequest(Infrastructure.TelhaNorteService.headerDTO auth, string documentID) {
            this.auth = auth;
            this.documentID = documentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerByDocumentID_Response", WrapperNamespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", IsWrapped=true)]
    public partial class getCustomerByDocumentIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Infrastructure.TelhaNorteService.customerDTO CustomerDTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.199.68.30/SGDBServicesAPI.API.SOAP:Services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Infrastructure.TelhaNorteService.returnDTO ReturnDTO;
        
        public getCustomerByDocumentIDResponse() {
        }
        
        public getCustomerByDocumentIDResponse(Infrastructure.TelhaNorteService.customerDTO CustomerDTO, Infrastructure.TelhaNorteService.returnDTO ReturnDTO) {
            this.CustomerDTO = CustomerDTO;
            this.ReturnDTO = ReturnDTO;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Services_PortTypeChannel : Infrastructure.TelhaNorteService.Services_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Services_PortTypeClient : System.ServiceModel.ClientBase<Infrastructure.TelhaNorteService.Services_PortType>, Infrastructure.TelhaNorteService.Services_PortType {
        
        public Services_PortTypeClient() {
        }
        
        public Services_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Services_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Services_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Services_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infrastructure.TelhaNorteService.activateOfferResponse Infrastructure.TelhaNorteService.Services_PortType.activateOffer(Infrastructure.TelhaNorteService.activateOfferRequest request) {
            return base.Channel.activateOffer(request);
        }
        
        public Infrastructure.TelhaNorteService.returnDTO activateOffer(Infrastructure.TelhaNorteService.headerDTO auth, Infrastructure.TelhaNorteService.offerDTO OfferDTO) {
            Infrastructure.TelhaNorteService.activateOfferRequest inValue = new Infrastructure.TelhaNorteService.activateOfferRequest();
            inValue.auth = auth;
            inValue.OfferDTO = OfferDTO;
            Infrastructure.TelhaNorteService.activateOfferResponse retVal = ((Infrastructure.TelhaNorteService.Services_PortType)(this)).activateOffer(inValue);
            return retVal.ReturnDTO;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.activateOfferResponse> Infrastructure.TelhaNorteService.Services_PortType.activateOfferAsync(Infrastructure.TelhaNorteService.activateOfferRequest request) {
            return base.Channel.activateOfferAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.activateOfferResponse> activateOfferAsync(Infrastructure.TelhaNorteService.headerDTO auth, Infrastructure.TelhaNorteService.offerDTO OfferDTO) {
            Infrastructure.TelhaNorteService.activateOfferRequest inValue = new Infrastructure.TelhaNorteService.activateOfferRequest();
            inValue.auth = auth;
            inValue.OfferDTO = OfferDTO;
            return ((Infrastructure.TelhaNorteService.Services_PortType)(this)).activateOfferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infrastructure.TelhaNorteService.getOrdersByDocumentIDResponse Infrastructure.TelhaNorteService.Services_PortType.getOrdersByDocumentID(Infrastructure.TelhaNorteService.getOrdersByDocumentIDRequest request) {
            return base.Channel.getOrdersByDocumentID(request);
        }
        
        public Infrastructure.TelhaNorteService.ordersDTO getOrdersByDocumentID(Infrastructure.TelhaNorteService.headerDTO auth, string documentID, System.Nullable<System.DateTime> referenceDateTime, System.Nullable<int> pageNumber, out Infrastructure.TelhaNorteService.returnDTO ReturnDTO) {
            Infrastructure.TelhaNorteService.getOrdersByDocumentIDRequest inValue = new Infrastructure.TelhaNorteService.getOrdersByDocumentIDRequest();
            inValue.auth = auth;
            inValue.documentID = documentID;
            inValue.referenceDateTime = referenceDateTime;
            inValue.pageNumber = pageNumber;
            Infrastructure.TelhaNorteService.getOrdersByDocumentIDResponse retVal = ((Infrastructure.TelhaNorteService.Services_PortType)(this)).getOrdersByDocumentID(inValue);
            ReturnDTO = retVal.ReturnDTO;
            return retVal.OrdersDTO;
        }
        
        public System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.getOrdersByDocumentIDResponse> getOrdersByDocumentIDAsync(Infrastructure.TelhaNorteService.getOrdersByDocumentIDRequest request) {
            return base.Channel.getOrdersByDocumentIDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infrastructure.TelhaNorteService.createUpdateCustomerResponse Infrastructure.TelhaNorteService.Services_PortType.createUpdateCustomer(Infrastructure.TelhaNorteService.createUpdateCustomerRequest request) {
            return base.Channel.createUpdateCustomer(request);
        }
        
        public Infrastructure.TelhaNorteService.returnDTO createUpdateCustomer(Infrastructure.TelhaNorteService.headerDTO auth, Infrastructure.TelhaNorteService.customerDTO CustomerDTO) {
            Infrastructure.TelhaNorteService.createUpdateCustomerRequest inValue = new Infrastructure.TelhaNorteService.createUpdateCustomerRequest();
            inValue.auth = auth;
            inValue.CustomerDTO = CustomerDTO;
            Infrastructure.TelhaNorteService.createUpdateCustomerResponse retVal = ((Infrastructure.TelhaNorteService.Services_PortType)(this)).createUpdateCustomer(inValue);
            return retVal.ReturnDTO;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.createUpdateCustomerResponse> Infrastructure.TelhaNorteService.Services_PortType.createUpdateCustomerAsync(Infrastructure.TelhaNorteService.createUpdateCustomerRequest request) {
            return base.Channel.createUpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.createUpdateCustomerResponse> createUpdateCustomerAsync(Infrastructure.TelhaNorteService.headerDTO auth, Infrastructure.TelhaNorteService.customerDTO CustomerDTO) {
            Infrastructure.TelhaNorteService.createUpdateCustomerRequest inValue = new Infrastructure.TelhaNorteService.createUpdateCustomerRequest();
            inValue.auth = auth;
            inValue.CustomerDTO = CustomerDTO;
            return ((Infrastructure.TelhaNorteService.Services_PortType)(this)).createUpdateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infrastructure.TelhaNorteService.getCustomerByDocumentIDResponse Infrastructure.TelhaNorteService.Services_PortType.getCustomerByDocumentID(Infrastructure.TelhaNorteService.getCustomerByDocumentIDRequest request) {
            return base.Channel.getCustomerByDocumentID(request);
        }
        
        public Infrastructure.TelhaNorteService.customerDTO getCustomerByDocumentID(Infrastructure.TelhaNorteService.headerDTO auth, string documentID, out Infrastructure.TelhaNorteService.returnDTO ReturnDTO) {
            Infrastructure.TelhaNorteService.getCustomerByDocumentIDRequest inValue = new Infrastructure.TelhaNorteService.getCustomerByDocumentIDRequest();
            inValue.auth = auth;
            inValue.documentID = documentID;
            Infrastructure.TelhaNorteService.getCustomerByDocumentIDResponse retVal = ((Infrastructure.TelhaNorteService.Services_PortType)(this)).getCustomerByDocumentID(inValue);
            ReturnDTO = retVal.ReturnDTO;
            return retVal.CustomerDTO;
        }
        
        public System.Threading.Tasks.Task<Infrastructure.TelhaNorteService.getCustomerByDocumentIDResponse> getCustomerByDocumentIDAsync(Infrastructure.TelhaNorteService.getCustomerByDocumentIDRequest request) {
            return base.Channel.getCustomerByDocumentIDAsync(request);
        }
    }
}
