//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.ZanthusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:managerIntegracao", ConfigurationName="ZanthusService.managerIntegracaoPortType")]
    public interface managerIntegracaoPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:managerIntegracao#metodoIntegracaoGenerico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string metodoIntegracaoGenerico(string str_xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:managerIntegracao#metodoIntegracaoGenerico", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> metodoIntegracaoGenericoAsync(string str_xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:managerIntegracao#metodoConsultaIntegracaoGenerico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string metodoConsultaIntegracaoGenerico(string str_xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:managerIntegracao#metodoConsultaIntegracaoGenerico", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> metodoConsultaIntegracaoGenericoAsync(string str_xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface managerIntegracaoPortTypeChannel : Infrastructure.ZanthusService.managerIntegracaoPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class managerIntegracaoPortTypeClient : System.ServiceModel.ClientBase<Infrastructure.ZanthusService.managerIntegracaoPortType>, Infrastructure.ZanthusService.managerIntegracaoPortType {
        
        public managerIntegracaoPortTypeClient() {
        }
        
        public managerIntegracaoPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public managerIntegracaoPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public managerIntegracaoPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public managerIntegracaoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string metodoIntegracaoGenerico(string str_xml) {
            return base.Channel.metodoIntegracaoGenerico(str_xml);
        }
        
        public System.Threading.Tasks.Task<string> metodoIntegracaoGenericoAsync(string str_xml) {
            return base.Channel.metodoIntegracaoGenericoAsync(str_xml);
        }
        
        public string metodoConsultaIntegracaoGenerico(string str_xml) {
            return base.Channel.metodoConsultaIntegracaoGenerico(str_xml);
        }
        
        public System.Threading.Tasks.Task<string> metodoConsultaIntegracaoGenericoAsync(string str_xml) {
            return base.Channel.metodoConsultaIntegracaoGenericoAsync(str_xml);
        }
    }
}
